/*
    Description: This program is a game inspired by Snake and Ladders. It is instead called Doggos, Ladders, Slides and U-turns. This game is heavily reliant on luck compared to the original game.
    Last modified: February 07, 2022
    Version: 1.0
*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

// This function calls the 10 sided dice.
int rollTenSidedDice(){
    return rand() % 10 + 1;
}

// This function computes for the tile generated by two 10 sided dice then returns the result.
int computeRandomTile(int *rowDice, int *columnDice){
    *rowDice = rollTenSidedDice();
    *columnDice = rollTenSidedDice();

    if (*rowDice % 2 == 0)
        return ((*rowDice - 1) * 10) + (11 - *columnDice);
    else 
        return (*rowDice * 10) - (10 - *columnDice);
}

/* This function validates if the input is between 2-5 players. 
If the input is correct it will return the value back. If not, it will keep asking the player to enter the right amount of players.*/
int validateNumberOfPlayers(int players){
    while (!(players >= 2 && players <= 5)) {
        printf("\nInvalid Input!\n");
        printf("Please choose from (2) to (5) players only!\n\n");
        printf("How many players will play this game (2-5): ");
        scanf("%d", &players);
    }
    
    return players;
}

/* This function checks for the amount of players then creates an array based on the 
amount of players which then shuffles the array randomly creating a random sequence.  
*/
void getPlayerSequence(int players, int resultSequence[]){
    int i, j, temp;
    int result[5];

    for (i = 0; i < players; i++)
        result[i] = i + 1;

    for (i = 0; i < players; i++){
        j = rand() % players;
        temp = result[i];
        result[i] = result[j];
        result[j] = temp;
    }

    for (i = 0; i < players; i++){
        // printf("%d", result[i]); //testing
        resultSequence[i] = result[i];
    }
}

int getCurrentPlayer(int players, int sequence){
    if (players == 2){

    }
    if (players == 3){

    }
    if (players == 4){

    }
    if (players == 5){

    }
    
}

void updateSequence(int players, int sequence[], int tempUpdateSequence[]){
    for(int i = 0; i < players; i++){
        if (i == 0)
            tempUpdateSequence[players - 1] = sequence[i];
        else
            tempUpdateSequence[i - 1] = sequence[i];
    }
}

int doggo(int *row, int *column){
    *row = rollTenSidedDice();
    *column = rollTenSidedDice();

    // printf("row dice: %d", *row);
    // printf("\ncolumn dice: %d\n", *column); //testing

    if (*row % 2 == 0) {
        printf("You found a Doggo. You followed the doggo to tile %d\n\n\n", ((*row - 1) * 10) + (11 - *column));
        return ((*row - 1) * 10) + (11 - *column);
    }
        
    else {
        printf("You found a Doggo. You followed the doggo to tile %d\n\n\n", ((*row - 1) * 10) + (11 - *column));
        return (*row * 10) - (10 - *column);
    }
}

int ladder(int position, int *row, int *column){
    *row = rollTenSidedDice();
    *column = rollTenSidedDice();
    int tileAbove;
    int resultBothDice;

    if (position >= 90){
        resultBothDice = position + *column;

        while (resultBothDice > 100){
            *column = rollTenSidedDice();
            resultBothDice = position + *column;
        }
        // printf("\n column dice: %d\n", *column); //testing
        printf("Lucky! You found a ladder. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }

    else if (*row % 2 == 0)
    {
        // if (position % 10 != 0) 
        //     tileAbove = (position - (position % 10)) + 10;
        // else
        //     tileAbove = (position);

        resultBothDice = ((*row - 1) * 10) + (11 - *column);

        while (resultBothDice <= position){
            *row = rollTenSidedDice();
            *column = rollTenSidedDice();
            
            if (*row % 2 == 0)
                resultBothDice = ((*row - 1) * 10) + (11 - *column);
            else 
                resultBothDice = (*row * 10) - (10 - *column);
        }
        // printf("row dice: %d", *row); //testing
        // printf("\ncolumn dice: %d\n", *column); //testing
        printf("Lucky! You found a ladder. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }
        
    else 
    {
        // if (position % 10 != 0) 
        //     tileAbove = (position - (position % 10)) + 10;
        // else
        //     tileAbove = (position);

        resultBothDice = (*row * 10) - (10 - *column);

        while (resultBothDice <= position){
            *row = rollTenSidedDice();
            *column = rollTenSidedDice();
            
            if (*row % 2 == 0)
                resultBothDice = ((*row - 1) * 10) + (11 - *column);
            else 
                resultBothDice = (*row * 10) - (10 - *column);
        }
        // printf("row dice: %d", *row); //testing
        // printf("\ncolumn dice: %d\n", *column); //testing
        printf("Lucky! You found a ladder. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }

}

int slide(int position, int *row, int *column){
    *row = rollTenSidedDice();
    *column = rollTenSidedDice();
    int tileBelow;
    int resultBothDice;

    if (position <= 10){
        resultBothDice = position - *column;

        while (resultBothDice < 1){
            *column = rollTenSidedDice();
            resultBothDice = position - *column;
        }
        // printf("\n dice: %d\n", *column); //testing
        printf("Unlucky! You found a slide. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }

    else if (*row % 2 == 0)
    {
        // if (position % 10 != 0) 
        //     tileBelow = (position - (position % 10));
        // else
        //     tileBelow = (position - 10);

        resultBothDice = ((*row - 1) * 10) + (11 - *column);

        while (resultBothDice >= position){
            *row = rollTenSidedDice();
            *column = rollTenSidedDice();
            
            if (*row % 2 == 0)
                resultBothDice = ((*row - 1) * 10) + (11 - *column);
            else 
                resultBothDice = (*row * 10) - (10 - *column);
        }
        // printf("row dice: %d", *row); //testing
        // printf("\ncolumn dice: %d\n", *column); //testing
        printf("Unlucky! You found a slide. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }
        
    else 
    {
        // if (position % 10 != 0) 
        //     tileBelow = (position - (position % 10));
        // else
        //     tileBelow = (position - 10);

        resultBothDice = (*row * 10) - (10 - *column);

        while (resultBothDice >= position){
            *row = rollTenSidedDice();
            *column = rollTenSidedDice();
            
            if (*row % 2 == 0)
                resultBothDice = ((*row - 1) * 10) + (11 - *column);
            else 
                resultBothDice = (*row * 10) - (10 - *column);
        }
        // printf("row dice: %d", *row); //testing
        // printf("\ncolumn dice: %d\n", *column); //testing
        printf("Unlucky! You found a slide. Proceed to tile %d\n\n\n", resultBothDice);
        return resultBothDice;
    }
}

int reverse(int currentPosition, int currentPlayer, int prevPosP1, int prevPosP2, int prevPosP3, int prevPosP4, int prevPosP5){
    if (currentPlayer == 1){
        if (currentPosition < prevPosP1)
            printf("Lucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP1);
        else if (currentPosition > prevPosP1)
            printf("Unlucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP1);
        else
            printf("You found U-Turn, but previous tile is the same as your current tile. You stay in tile %d.\n\n\n", prevPosP1);
        return prevPosP1;
    }

    if (currentPlayer == 2){
        if (currentPosition < prevPosP2)
            printf("Lucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP2);
        else if (currentPosition > prevPosP2)
            printf("Unlucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP2);
        else
            printf("You found U-Turn, but previous tile is the same as your current tile. You stay in tile %d.\n\n\n", prevPosP2);
        return prevPosP2;
    }

    if (currentPlayer == 3){
        if (currentPosition < prevPosP3)
            printf("Lucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP3);
        else if (currentPosition > prevPosP3)
            printf("Unlucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP3);
        else
            printf("You found U-Turn, but previous tile is the same as your current tile. You stay in tile %d.\n\n\n", prevPosP3);
        return prevPosP3;
    }

    if (currentPlayer == 4){
        if (currentPosition < prevPosP4)
            printf("Lucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP4);
        else if (currentPosition > prevPosP4)
            printf("Unlucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP4);
        else
            printf("You found U-Turn, but previous tile is the same as your current tile. You stay in tile %d.\n\n\n", prevPosP4);
        return prevPosP4;
    }

    if (currentPlayer == 5){
        if (currentPosition < prevPosP5)
            printf("Lucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP5);
        else if (currentPosition > prevPosP5)
            printf("Unlucky! You found U-Turn. You go back to tile %d.\n\n\n", prevPosP5);
        else
            printf("You found U-Turn, but previous tile is the same as your current tile. You stay in tile %d.\n\n\n", prevPosP5);
        return prevPosP5;
    }
}

// check if there is an object in a tile.
int checkTileObject(int playerPosition, int currentPlayer, int prevPosP1, int prevPosP2, int prevPosP3, int prevPosP4, int prevPosP5, int *row, int *column){
    int dice;
    int countDoggo = 0;

    dice = rollTenSidedDice();

    // printf("dice: %d\n", dice);
    

    if (dice == 1)
    {
        countDoggo++;
        return doggo(row, column);
    }
    else if (dice == 2)
    {
        return ladder(playerPosition, row, column);
    }

    else if (dice == 3)
    {
        return slide(playerPosition, row, column);
    }

    else if (dice == 4)
    {
        return reverse(playerPosition, currentPlayer, prevPosP1, prevPosP2, prevPosP3, prevPosP4, prevPosP5);
    }
    else
    {
        printf("You did not find any object, so you stay in the same tile.\n\n\n");
        return playerPosition;
    }
}

void transferCurrentPositionToPlayer(int currentPlayer, int currentPosition, int *P1_position, int *P2_position, int *P3_position, int *P4_position, int *P5_position){
    if (currentPlayer == 1){
        *P1_position = currentPosition;
    }
    if (currentPlayer == 2){
        *P2_position = currentPosition;
    }
    if (currentPlayer == 3){
        *P3_position = currentPosition;
    }
    if (currentPlayer == 4){
        *P4_position = currentPosition;
    }
    if (currentPlayer == 5){
        *P5_position = currentPosition;
    }
}

void storePrevPlayerPosition(int curPosP1, int curPosP2, int curPosP3, int curPosP4, int curPosP5, int *prevPosP1, int *prevPosP2, int *prevPosP3, int *prevPosP4, int *prevPosP5){
    *prevPosP1 = curPosP1;
    *prevPosP2 = curPosP2;
    *prevPosP3 = curPosP3;
    *prevPosP4 = curPosP4;
    *prevPosP5 = curPosP5;
}

void storePrevRowColumn(int currentPlayer, int row, int column, int *prevRowP1, int *prevRowP2, int *prevRowP3, int *prevRowP4, int *prevRowP5, int *prevColumnP1, int *prevColumnP2, int *prevColumnP3, int *prevColumnP4, int *prevColumnP5){
    if (currentPlayer == 1){
        *prevRowP1 = row;
        *prevColumnP1 = column;
    }
    if (currentPlayer == 2){
        *prevRowP2 = row;
        *prevColumnP2 = column;
    }
    if (currentPlayer == 3){
        *prevRowP3 = row;
        *prevColumnP3 = column;
    }
    if (currentPlayer == 4){
        *prevRowP4 = row;
        *prevColumnP4 = column;
    }
    if (currentPlayer == 5){
        *prevRowP5 = row;
        *prevColumnP5 = column;
    }
}

int checkEvenRow(int row){
    if (row % 2 == 0)
        return 1;
    else
        return 0;
}

int rowThreeColumnThree(int position, int currentPlayer, int prevRowP1, int prevRowP2, int prevRowP3, int prevRowP4, int prevRowP5, int prevColumnP1, int prevColumnP2, int prevColumnP3, int prevColumnP4, int prevColumnP5){
    if (currentPlayer == 1){
        if (checkEvenRow(prevRowP1))
            return position + 20 + ((2 * prevColumnP1) - 1);
        else
            return position + 40 - ((2 * prevColumnP1) - 1);
    }
    else if (currentPlayer == 2){
        if (checkEvenRow(prevRowP2))
            return position + 20 + ((2 * prevColumnP2) - 1);
        else
            return position + 40 - ((2 * prevColumnP2) - 1);
    }
    else if (currentPlayer == 3){
        if (checkEvenRow(prevRowP3))
            return position + 20 + ((2 * prevColumnP3) - 1);
        else
            return position + 40 - ((2 * prevColumnP4) - 1);
    }
    else if (currentPlayer == 4){
        if (checkEvenRow(prevRowP4))
            return position + 20 + ((2 * prevColumnP4) - 1);
        else
            return position + 40 - ((2 * prevColumnP4) - 1);
    }
    else{
        if (checkEvenRow(prevRowP5))
            return position + 20 + ((2 * prevColumnP5) - 1);
        else
            return position + 40 - ((2 * prevColumnP5) - 1);
    }
}

int checkPlayerEligiblePairThree(int currentPlayer, int playerPos1, int playerPos2, int playerPos3, int playerPos4, int playerPos5){
    if (currentPlayer == 1){
        if (playerPos1 == 0)
            return 1;
        else if (playerPos1 >= 71)
            return 1;
        else
            return 0;
    }
    
    if (currentPlayer == 2){
        if (playerPos2 == 0)
            return 1;
        else if (playerPos2 >= 71)
            return 1;
        else
            return 0;
    }

    if (currentPlayer == 3){
        if (playerPos3 == 0)
            return 1;
        else if (playerPos3 >= 71)
            return 1;
        else
            return 0;
    }

    if (currentPlayer == 4){
        if (playerPos4 == 0)
            return 1;
        else if (playerPos4 >= 71)
            return 1;
        else
            return 0;
    }

    if (currentPlayer == 5){
        if (playerPos5 == 0)
            return 1;
        else if (playerPos5 >= 71)
            return 1;
        else
            return 0;
    }
}

void getPlayerPairThree(int currentPlayer, int *curPosPlayer1, int *curPosPlayer2, int *curPosPlayer3, int *curPosPlayer4, int *curPosPlayer5){
    if (currentPlayer == 1)
        *curPosPlayer1;
    if (currentPlayer == 2)
        *curPosPlayer2;
    if (currentPlayer == 3)
        *curPosPlayer3;
    if (currentPlayer == 4)
        *curPosPlayer4;
    if (currentPlayer == 5)
        *curPosPlayer5;
}

int rowFiveColumnFive(int currentPlayer, int playerPosition1, int playerPosition2, int playerPosition3, int playerPosition4, int playerPosition5){
    if (currentPlayer == 1)
        return playerPosition1;
    else if (currentPlayer == 2)
        return playerPosition2;
    else if (currentPlayer == 3)
        return playerPosition3;
    else if (currentPlayer == 4)
        return playerPosition4;
    else 
        return playerPosition5;
}

int checkAmountPlayerSameTile(int boardTile, int playerPosition1, int playerPosition2, int playerPosition3, int playerPosition4, int playerPosition5){
    int amountPlayerTile = 0;

    if (playerPosition1 == boardTile)
        amountPlayerTile++;

    if (playerPosition2 == boardTile)
        amountPlayerTile++;

    if (playerPosition3 == boardTile)
        amountPlayerTile++;

    if (playerPosition4 == boardTile)
        amountPlayerTile++;

    if (playerPosition5 == boardTile)
        amountPlayerTile++;

    return amountPlayerTile;
    
} 

void printPlayerSameTile(int boardTile, int playerPosition1, int playerPosition2, int playerPosition3, int playerPosition4, int playerPosition5){
    if (playerPosition1 == boardTile)
        printf("P1");

    if (playerPosition2 == boardTile)
        printf("P2");

    if (playerPosition3 == boardTile)
        printf("P3");

    if (playerPosition4 == boardTile)
        printf("P4");

    if (playerPosition5 == boardTile)
        printf("P5");
}

void printFrontSpace (int amountPlayer){
    if (amountPlayer == 1)
        printf("      ");
    if (amountPlayer == 2)
        printf("     ");
    if (amountPlayer == 3)
        printf("    ");
    if (amountPlayer == 4)
        printf("   ");
    if (amountPlayer == 5)
        printf("  ");
}

void printBackSpace (int amountPlayer){
    if (amountPlayer == 1)
        printf("      ||");
    if (amountPlayer == 2)
        printf("     ||");
    if (amountPlayer == 3)
        printf("    ||");
    if (amountPlayer == 4)
        printf("   ||");
    if (amountPlayer == 5)
        printf("  ||");
}

void board(int posPlayer1, int posPlayer2, int posPlayer3, int posPlayer4, int posPlayer5){
    int boardNum = 100;
    int plusNum = 1;
    int minusNum = 10;
    int tileResult;
    int playerPosition;
    int playersInTile = 0;

    for(int i = 1; i <= 10; i++){
        for (int j = 1; j <= 10; j++){

            if (i <= 10 && j == 1)
                    printf("\t\t\t||");

            if (i % 2 == 1){
                if(i == 1 && j == 1){

                    if (boardNum == posPlayer1 || boardNum == posPlayer2 || boardNum == posPlayer3 || boardNum == posPlayer4 || boardNum == posPlayer5) {
                        playersInTile = checkAmountPlayerSameTile(boardNum, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printFrontSpace (playersInTile);
                        printPlayerSameTile(boardNum, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printBackSpace (playersInTile);
                    }
                        
                    else
                        printf("     %3d      ||", boardNum);
                }

                else{

                    if (boardNum == posPlayer1 || boardNum == posPlayer2 || boardNum == posPlayer3 || boardNum == posPlayer4 || boardNum == posPlayer5) {
                        playersInTile = checkAmountPlayerSameTile(boardNum, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printFrontSpace (playersInTile);
                        printPlayerSameTile(boardNum, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printBackSpace (playersInTile);
                    }

                    else
                        printf("      %2d      ||", boardNum);
                }
            }
            
            else {

                if (j == 10) {
                    tileResult = (boardNum - minusNum) + plusNum;
                    playersInTile = checkAmountPlayerSameTile(tileResult, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);

                    if (playersInTile >= 1){
                        printFrontSpace (playersInTile);
                        printPlayerSameTile(tileResult, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printBackSpace (playersInTile);
                    }

                    else
                        printf("      %2d      ||", tileResult);
                    
                    plusNum+=2;
                    minusNum+=20;
                }


                else{
                    tileResult = (boardNum - minusNum) + plusNum;
                    playersInTile = checkAmountPlayerSameTile(tileResult, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);

                    if (playersInTile >= 1){
                        printFrontSpace (playersInTile);
                        printPlayerSameTile(tileResult, posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5);
                        printBackSpace (playersInTile);
                    }

                    else
                        printf("      %2d      ||", tileResult);
                    plusNum+=2;
                }
            }
            boardNum--;
            playersInTile = 0;
        }
        printf("\n");
    }
}

// This function prints the ranking of all players depending on the total number of players. 
void printRank(int players, int greaterP1, int greaterP2, int greaterP3, int greaterP4, int greaterP5) {
    int rank[] = {greaterP1, greaterP2, greaterP3, greaterP4, greaterP5};
    int a = players - 1;

    printf("\t\t\t||    RANK    ||   PLAYER   ||\n");
    for (int i = 1; i <= players; i++) {
        if (rank[0] == a)
            printf("\t\t\t||      %d     ||     P1     ||\n", i);

        if (rank[1] == a)
            printf("\t\t\t||      %d     ||     P2     ||\n", i);
        
        if (players == 3 || players == 4 || players == 5) {
            if (rank[2] == a)
                printf("\t\t\t||      %d     ||     P3     ||\n", i);
        }

        if (players == 4 || players == 5) {
            if (rank[3] == a)
                printf("\t\t\t||      %d     ||     P4     ||\n", i);
        }

        if (players == 5) {
            if (rank[4] == a)
                printf("\t\t\t||      %d     ||     P5     ||\n", i);
        }
        a--;
    }
}

/* This function compares each players position. For every higher tile from one player's position, it will give a tally
which will then be used to call printRank function.
*/
void compareRank(int players, int posPlayer1, int posPlayer2, int posPlayer3, int posPlayer4, int posPlayer5){
    int playerScores[] = {posPlayer1, posPlayer2, posPlayer3, posPlayer4, posPlayer5};
    int greaterP1 = 0;
    int greaterP2 = 0;
    int greaterP3 = 0;
    int greaterP4 = 0;
    int greaterP5 = 0;

    if (players == 2){
        if (playerScores[0] > playerScores[1])
            greaterP1++;
        if (playerScores[1] > playerScores[0])
            greaterP2++;
    }

    if (players == 3){
        for (int i = 1; i < players; i++) {
            if (playerScores[0] > playerScores[i])
                greaterP1++;

            if (i >= 2){
                if (playerScores[1] > playerScores[i])
                    greaterP2++;
            }
            else if (playerScores[1] > playerScores[i - 1])
                greaterP2++;

            if (playerScores[2] > playerScores[i - 1])
                greaterP3++;
            
        }
    }

    if(players == 4){
        for (int i = 1; i < players; i++) {
            if (playerScores[0] > playerScores[i])
                greaterP1++;

            if (i >= 2){
                if (playerScores[1] > playerScores[i])
                    greaterP2++;
            }
            else if (playerScores[1] > playerScores[i - 1])
                greaterP2++;

            if (i >= 3){
                if (playerScores[2] > playerScores[i])
                    greaterP3++;
            }
            else if (playerScores[2] > playerScores[i - 1])
                greaterP3++;
            
            if (playerScores[3] > playerScores[i - 1])
                greaterP4++;
        }
    }

    if(players == 5){
        for (int i = 1; i < players; i++) {
            if (playerScores[0] > playerScores[i])
                greaterP1++;

            if (i >= 2){
                if (playerScores[1] > playerScores[i])
                    greaterP2++;
            }
            else if (playerScores[1] > playerScores[i - 1])
                greaterP2++;

            if (i >= 3){
                if (playerScores[2] > playerScores[i])
                    greaterP3++;
            }
            else if (playerScores[2] > playerScores[i - 1])
                greaterP3++;

            if (i >= 4){
                if (playerScores[3] > playerScores[i])
                    greaterP4++;
            }
            else if (playerScores[3] > playerScores[i - 1])
                greaterP4++;
            
            if (playerScores[4] > playerScores[i - 1])
                greaterP5++;
        }
    }

    printRank(players, greaterP1, greaterP2, greaterP3, greaterP4, greaterP5);
}
    
void summary(){

}

int main(){

    int again = 1;

    do {
        srand(time(NULL));

        int players;
        int sequence[5];
        int tempUpdateSequence[5];
        int tempTwoUpdateSequence[5];
        int currentPlayer;

        int curPosPlayer1 = 0;
        int curPosPlayer2 = 0;
        int curPosPlayer3 = 0;
        int curPosPlayer4 = 0;
        int curPosPlayer5 = 0;

        int prevPosPlayer1 = 0;
        int prevPosPlayer2 = 0;
        int prevPosPlayer3 = 0;
        int prevPosPlayer4 = 0;
        int prevPosPlayer5 = 0;

        int position;
        int currentPosition = 0;
        int previousPosition = 0;
        int reply;
        int boardReply;
        int rankReply;
        int ready;

        int round = 1;

        int diceOne = 0;
        int diceTwo = 0;

        int prevColumnP1 = 0;
        int prevColumnP2 = 0;
        int prevColumnP3 = 0;
        int prevColumnP4 = 0;
        int prevColumnP5 = 0;

        int prevRowP1 = 0;
        int prevRowP2 = 0;
        int prevRowP3 = 0;
        int prevRowP4 = 0;
        int prevRowP5 = 0;

        int confirmObject = 0;

        int winner;

        printf("\n\n\nWelcome to Doggos, Ladders, Slides and U-turns!");
        printf("\nHow many players will play this game (2-5): ");
        scanf("%d", &players);
        players = validateNumberOfPlayers(players);
        
        getPlayerSequence(players, sequence);

        while (curPosPlayer1 != 100 && curPosPlayer2 != 100 && curPosPlayer3 != 100 && curPosPlayer4 != 100 && curPosPlayer5 != 100) {
            for (int i = 0; i < players; i++)
            {
                currentPlayer = sequence[i];

                // This will only be executed at the start of the game.
                if(round == 1 && i == 0){
                    printf("\nThe game starts with"); 

                    for (int a = 0; a < players; a++){   
                        if (a == (players - 1))
                            printf(" then Player %d.", sequence[a]);
                        else
                            printf(" Player %d,", sequence[a]);
            
                    }
                }

                else{
                    if(i == 1)
                        updateSequence(players, sequence, tempUpdateSequence);
                    updateSequence(players, tempUpdateSequence, tempTwoUpdateSequence);

                    printf("\nUpdated sequence: ");
                    for(int h = 0; h < players; h++){
                        if (round >= 2 && i == 0)
                            printf("%d", sequence[h]);
                        else if(round >= 1 && i == 1)
                            printf("%d", tempUpdateSequence[h]);
                        else{
                            printf("%d", tempTwoUpdateSequence[h]);
                            for (int j = 0; j < players; j++)
                                tempUpdateSequence[j] = tempTwoUpdateSequence[j]; 
                        }
                    }
                }
                printf("\nRound: %d Player: %d \n\n", round, currentPlayer);

                printf("Player %d are you ready to roll? [1]Yes or [0]No: ", currentPlayer);
                scanf("%d", &ready);
                
                while (ready != 1){
                    if (ready == 0){
                        printf("\t\tHow about now? [1]Yes or [0]No: ");
                    }

                    else{
                        printf("\t\tInvalid Input!\n");
                        printf("\t\tPlease enter [1]Yes or [0]No only! ");
                    }
                scanf("%d", &ready);
                }

                if (ready == 1){
                    currentPosition = computeRandomTile(&diceOne, &diceTwo);
                    

                    if (diceOne == 3 && diceTwo == 3){
                        if (checkPlayerEligiblePairThree(currentPlayer, curPosPlayer1, curPosPlayer2, curPosPlayer3, curPosPlayer4, curPosPlayer5) == 1){
                            getPlayerPairThree(currentPlayer, &curPosPlayer1, &curPosPlayer2, &curPosPlayer3, &curPosPlayer4, &curPosPlayer5);
                            printf("You rolled a double 3. Unfortunately, you cannot move 3 rows above due to the tile being non-existent. \n\n\n");
                        }

                        else{
                            currentPosition = rowThreeColumnThree(currentPosition, currentPlayer, prevRowP1, prevRowP2, prevRowP3, prevRowP4, prevRowP5, prevColumnP1, prevColumnP2, prevColumnP3, prevColumnP4, prevColumnP5);
                            printf("Lucky!!! You rolled a double 3. Please proceed to tile %d. \n\n\n", currentPosition);
                        }
                            
                    }
                
                    else if (diceOne == 5 && diceTwo == 5){
                        rowFiveColumnFive(currentPlayer, curPosPlayer1, curPosPlayer2, curPosPlayer3, curPosPlayer4, curPosPlayer5);
                        printf("Unlucky. You rolled a double 5. You skipped a turn.\n\n\n");
                    }

                    else{
                        printf("\nYou rolled : %d & %d", diceOne, diceTwo);
                        printf("\nPlayer %d moves to tile %d\n", currentPlayer, currentPosition);

                        currentPosition = checkTileObject(currentPosition, currentPlayer, prevPosPlayer1, prevPosPlayer2, prevPosPlayer3, prevPosPlayer4, prevPosPlayer5, &diceOne, &diceTwo);
                    }

                }

                storePrevRowColumn(currentPlayer, diceOne, diceTwo, &prevRowP1, &prevRowP2, &prevRowP3, &prevRowP4, &prevRowP5, &prevColumnP1, &prevColumnP2, &prevColumnP3, &prevColumnP4, &prevColumnP5);

                if (curPosPlayer1 == 100 || curPosPlayer2 == 100 || curPosPlayer3 == 100 || curPosPlayer4 == 100 || curPosPlayer5 == 100){
                    winner = currentPlayer;
                    i = players;
                }
                    
                
                transferCurrentPositionToPlayer(currentPlayer, currentPosition, &curPosPlayer1, &curPosPlayer2, &curPosPlayer3, &curPosPlayer4, &curPosPlayer5);

            }
            round++;
            storePrevPlayerPosition(curPosPlayer1, curPosPlayer2, curPosPlayer3, curPosPlayer4, curPosPlayer5, &prevPosPlayer1, &prevPosPlayer2, &prevPosPlayer3, &prevPosPlayer4, &prevPosPlayer5);
            
            

            printf("\n\n\nShow Board? (1) Yes or (0) No:");
            scanf("%d", &boardReply);

            while (boardReply != 1 && boardReply != 0 ){
                printf("\nInvalid input!\n Please only input (1) Yes or (0) No: ");
                scanf("%d", &boardReply);
            }

            if (boardReply == 1 ){
                board(curPosPlayer1, curPosPlayer2, curPosPlayer3, curPosPlayer4, curPosPlayer5);
            }



            printf("\n\nShow players rank? (1) Yes or (0) No: ");
            scanf("%d", &rankReply);

            while (rankReply != 1 && rankReply != 0){
                printf("\nInvalid input!\n Please only input (1) Yes or (0) No:\n");
                scanf("%d", &rankReply);
            }

            if (rankReply == 1){
                compareRank(players, curPosPlayer1, curPosPlayer2, curPosPlayer3, curPosPlayer4, curPosPlayer5);
            }

            else {
                printf("Next Round!");
            }
            
            
            //     previousPosition = currentPosition;
            
            if (curPosPlayer1 == 100 || curPosPlayer2 == 100 || curPosPlayer3 == 100 || curPosPlayer4 == 100 || curPosPlayer5 == 100){

                printf("\n\n\n\n\nCongratulations!!! You won the game Player %d", winner);

                printf("\nDo you want to play again? (1) Yes (0) No : ");
                scanf("%d", &again);
            
                while ( !(again >= 0 && again <= 1) ){
                printf("\nInvalid input! Please only input (1) or (0).");

                printf("\nDo you want to play another game? (1) Yes (0) No : ");
                scanf("%d", &again);
                }
            }
        }
    } while (again == 1);

    return 0;
}